Transform: AWS::Serverless-2016-10-31
Resources:
  UserSignup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoSignupLambda::handleRequest
      FunctionName: CognitoSignupLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/signup
            Method: post
  RefreshTokens:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoRefreshTokensLambda::handleRequest
      FunctionName: CognitoRefreshTokensLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/refresh
            Method: post
  UserSignin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoSigninLambda::handleRequest
      FunctionName: CognitoSigninLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/signin
            Method: post
  UserDelete:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoDeleteUserLambda::handleRequest
      FunctionName: CognitoDeleteUserLambda
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/user
            Method: delete
  CheckTokenValidity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoTokenValidLambda::handleRequest
      FunctionName: CognitoTokenValidLambda
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/user/token/valid
            Method: get
  ResetPassword:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoResetPassword::handleRequest
      FunctionName: CognitoResetPassword
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: REGION_CHANGE_ME
          COGNITO_USER_POOL_ID: POOL_ID_CHANGE_ME
          COGNITO_APP_CLIENT_ID: CLIENT_ID_CHANGE_ME
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /cognito/user/password/reset
            Method: post
