Transform: AWS::Serverless-2016-10-31
Parameters:
  RegionParameter:
    Type: String
    Default: us-east-1
  CognitoUserPoolIdParameter:
    Type: String
    Default: us-east-1_PGSbCVZ7S
  CognitoAppClientIdParameter:
    Type: String
    Default: hikoo0i7jmt9lplrd2j0n9jqo
Resources:
  UserSignup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoSignupLambda::handleRequest
      FunctionName: CognitoSignupLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 20
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /signup
            Method: post
  RefreshTokens:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoRefreshTokensLambda::handleRequest
      FunctionName: CognitoRefreshTokensLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /refresh
            Method: post
  UserSignin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoSigninLambda::handleRequest
      FunctionName: CognitoSigninLambda
      Policies:
       - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /signin
            Method: post
  UserDelete:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoDeleteUserLambda::handleRequest
      FunctionName: CognitoDeleteUserLambda
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user
            Method: delete
  CheckTokenValidity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoTokenValidLambda::handleRequest
      FunctionName: CognitoTokenValidLambda
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/token/valid
            Method: get
  ResetPassword:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.cognito.lambda.CognitoResetPassword::handleRequest
      FunctionName: CognitoResetPassword
      Policies:
             - AmazonCognitoPowerUser
      Runtime: java8
      MemorySize: 1024
      Timeout: 15
      CodeUri: build/libs/cognito-rest-service-1.0-SNAPSHOT.jar
      Environment:
        Variables:
        Variables:
          REGION_NAME: 
            Ref: RegionParameter
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolIdParameter
          COGNITO_APP_CLIENT_ID:
            Ref: CognitoAppClientIdParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/password/reset
            Method: post
